[2024-12-09T00:36:41.554+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T00:36:41.568+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_dag.task_ingest_messages_data manual__2024-12-09T00:36:37.055064+00:00 [queued]>
[2024-12-09T00:36:41.575+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_dag.task_ingest_messages_data manual__2024-12-09T00:36:37.055064+00:00 [queued]>
[2024-12-09T00:36:41.576+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-09T00:36:41.588+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): task_ingest_messages_data> on 2024-12-09 00:36:37.055064+00:00
[2024-12-09T00:36:41.601+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_dag', 'task_ingest_messages_data', 'manual__2024-12-09T00:36:37.055064+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpheq5xzdx']
[2024-12-09T00:36:41.607+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask task_ingest_messages_data
[2024-12-09T00:36:41.600+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T00:36:41.609+0000] {standard_task_runner.py:72} INFO - Started process 121 to run task
[2024-12-09T00:36:41.699+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_dag.task_ingest_messages_data manual__2024-12-09T00:36:37.055064+00:00 [running]> on host 58979770e908
[2024-12-09T00:36:41.846+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_dag' AIRFLOW_CTX_TASK_ID='task_ingest_messages_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T00:36:37.055064+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T00:36:37.055064+00:00'
[2024-12-09T00:36:41.850+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T00:36:41.900+0000] {execute.py:83} INFO - Input Notebook:  /opt/***/dataset/cleanup_messages.ipynb
[2024-12-09T00:36:41.900+0000] {execute.py:84} INFO - Output Notebook: /opt/***/dataset/output_cleanup_messages.ipynb
[2024-12-09T00:36:42.033+0000] {execute.py:97} WARNING - Passed unknown parameter: file_path
[2024-12-09T00:36:42.033+0000] {execute.py:97} WARNING - Passed unknown parameter: sheet_name
[2024-12-09T00:36:42.045+0000] {parameterize.py:114} WARNING - Input notebook does not contain a cell with tag 'parameters'
[2024-12-09T00:36:42.069+0000] {logging_mixin.py:190} WARNING - Executing:   0%|          | 0/6 [00:00<?, ?cell/s]
[2024-12-09T00:36:44.678+0000] {clientwrap.py:44} INFO - Executing notebook with kernel: python3
[2024-12-09T00:36:44.700+0000] {logging_mixin.py:190} WARNING - Executing:  17%|#6        | 1/6 [00:02<00:13,  2.63s/cell]
[2024-12-09T00:36:48.353+0000] {logging_mixin.py:190} WARNING - Executing:  33%|###3      | 2/6 [00:06<00:12,  3.23s/cell]
[2024-12-09T00:36:48.667+0000] {logging_mixin.py:190} WARNING - Executing:  50%|#####     | 3/6 [00:06<00:05,  1.90s/cell]
[2024-12-09T00:36:48.977+0000] {logging_mixin.py:190} WARNING - Executing:  83%|########3 | 5/6 [00:06<00:00,  1.10cell/s]
[2024-12-09T00:36:49.293+0000] {logging_mixin.py:190} WARNING - Executing:  83%|########3 | 5/6 [00:07<00:01,  1.44s/cell]
[2024-12-09T00:36:49.302+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/resources/util_read_insert_data.py", line 41, in load_excel_to_db
    cleaned_data = process_notebook_and_generate_csv(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/resources/util_read_insert_data.py", line 17, in process_notebook_and_generate_csv
    pm.execute_notebook(
  File "/home/airflow/.local/lib/python3.12/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[4], line 1
----> 1 msg = pd.read_excel("Senior Data Engineer Task Assignment.xlsx", sheet_name="Messages")
      2 msg.drop_duplicates(subset=["id"], inplace=True)

File ~/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py:504, in read_excel(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend, engine_kwargs)
    502 if not isinstance(io, ExcelFile):
    503     should_close = True
--> 504     io = ExcelFile(
    505         io,
    506         storage_options=storage_options,
    507         engine=engine,
    508         engine_kwargs=engine_kwargs,
    509     )
    510 elif engine and engine != io.engine:
    511     raise ValueError(
    512         "Engine should not be specified when passing "
    513         "an ExcelFile - ExcelFile already has the engine set"
    514     )

File ~/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py:1563, in ExcelFile.__init__(self, path_or_buffer, engine, storage_options, engine_kwargs)
   1561     ext = "xls"
   1562 else:
-> 1563     ext = inspect_excel_format(
   1564         content_or_path=path_or_buffer, storage_options=storage_options
   1565     )
   1566     if ext is None:
   1567         raise ValueError(
   1568             "Excel file format cannot be determined, you must specify "
   1569             "an engine manually."
   1570         )

File ~/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py:1419, in inspect_excel_format(content_or_path, storage_options)
   1416 if isinstance(content_or_path, bytes):
   1417     content_or_path = BytesIO(content_or_path)
-> 1419 with get_handle(
   1420     content_or_path, "rb", storage_options=storage_options, is_text=False
   1421 ) as handle:
   1422     stream = handle.handle
   1423     stream.seek(0)

File ~/.local/lib/python3.12/site-packages/pandas/io/common.py:872, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    863         handle = open(
    864             handle,
    865             ioargs.mode,
   (...)
    868             newline="",
    869         )
    870     else:
    871         # Binary mode
--> 872         handle = open(handle, ioargs.mode)
    873     handles.append(handle)
    875 # Convert BytesIO or file objects passed with an encoding

FileNotFoundError: [Errno 2] No such file or directory: 'Senior Data Engineer Task Assignment.xlsx'

[2024-12-09T00:36:49.321+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=data_ingestion_dag, task_id=task_ingest_messages_data, run_id=manual__2024-12-09T00:36:37.055064+00:00, execution_date=20241209T003637, start_date=20241209T003641, end_date=20241209T003649
[2024-12-09T00:36:49.331+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T00:36:49.332+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 46 for task task_ingest_messages_data (
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[4], line 1
----> 1 msg = pd.read_excel("Senior Data Engineer Task Assignment.xlsx", sheet_name="Messages")
      2 msg.drop_duplicates(subset=["id"], inplace=True)

File ~/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py:504, in read_excel(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend, engine_kwargs)
    502 if not isinstance(io, ExcelFile):
    503     should_close = True
--> 504     io = ExcelFile(
    505         io,
    506         storage_options=storage_options,
    507         engine=engine,
    508         engine_kwargs=engine_kwargs,
    509     )
    510 elif engine and engine != io.engine:
    511     raise ValueError(
    512         "Engine should not be specified when passing "
    513         "an ExcelFile - ExcelFile already has the engine set"
    514     )

File ~/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py:1563, in ExcelFile.__init__(self, path_or_buffer, engine, storage_options, engine_kwargs)
   1561     ext = "xls"
   1562 else:
-> 1563     ext = inspect_excel_format(
   1564         content_or_path=path_or_buffer, storage_options=storage_options
   1565     )
   1566     if ext is None:
   1567         raise ValueError(
   1568             "Excel file format cannot be determined, you must specify "
   1569             "an engine manually."
   1570         )

File ~/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py:1419, in inspect_excel_format(content_or_path, storage_options)
   1416 if isinstance(content_or_path, bytes):
   1417     content_or_path = BytesIO(content_or_path)
-> 1419 with get_handle(
   1420     content_or_path, "rb", storage_options=storage_options, is_text=False
   1421 ) as handle:
   1422     stream = handle.handle
   1423     stream.seek(0)

File ~/.local/lib/python3.12/site-packages/pandas/io/common.py:872, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    863         handle = open(
    864             handle,
    865             ioargs.mode,
   (...)
    868             newline="",
    869         )
    870     else:
    871         # Binary mode
--> 872         handle = open(handle, ioargs.mode)
    873     handles.append(handle)
    875 # Convert BytesIO or file objects passed with an encoding

FileNotFoundError: [Errno 2] No such file or directory: 'Senior Data Engineer Task Assignment.xlsx'
; 121)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/resources/util_read_insert_data.py", line 41, in load_excel_to_db
    cleaned_data = process_notebook_and_generate_csv(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/resources/util_read_insert_data.py", line 17, in process_notebook_and_generate_csv
    pm.execute_notebook(
  File "/home/airflow/.local/lib/python3.12/site-packages/papermill/execute.py", line 131, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/papermill/execute.py", line 251, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [4]":
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[4], line 1
----> 1 msg = pd.read_excel("Senior Data Engineer Task Assignment.xlsx", sheet_name="Messages")
      2 msg.drop_duplicates(subset=["id"], inplace=True)

File ~/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py:504, in read_excel(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend, engine_kwargs)
    502 if not isinstance(io, ExcelFile):
    503     should_close = True
--> 504     io = ExcelFile(
    505         io,
    506         storage_options=storage_options,
    507         engine=engine,
    508         engine_kwargs=engine_kwargs,
    509     )
    510 elif engine and engine != io.engine:
    511     raise ValueError(
    512         "Engine should not be specified when passing "
    513         "an ExcelFile - ExcelFile already has the engine set"
    514     )

File ~/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py:1563, in ExcelFile.__init__(self, path_or_buffer, engine, storage_options, engine_kwargs)
   1561     ext = "xls"
   1562 else:
-> 1563     ext = inspect_excel_format(
   1564         content_or_path=path_or_buffer, storage_options=storage_options
   1565     )
   1566     if ext is None:
   1567         raise ValueError(
   1568             "Excel file format cannot be determined, you must specify "
   1569             "an engine manually."
   1570         )

File ~/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py:1419, in inspect_excel_format(content_or_path, storage_options)
   1416 if isinstance(content_or_path, bytes):
   1417     content_or_path = BytesIO(content_or_path)
-> 1419 with get_handle(
   1420     content_or_path, "rb", storage_options=storage_options, is_text=False
   1421 ) as handle:
   1422     stream = handle.handle
   1423     stream.seek(0)

File ~/.local/lib/python3.12/site-packages/pandas/io/common.py:872, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    863         handle = open(
    864             handle,
    865             ioargs.mode,
   (...)
    868             newline="",
    869         )
    870     else:
    871         # Binary mode
--> 872         handle = open(handle, ioargs.mode)
    873     handles.append(handle)
    875 # Convert BytesIO or file objects passed with an encoding

FileNotFoundError: [Errno 2] No such file or directory: 'Senior Data Engineer Task Assignment.xlsx'

[2024-12-09T00:36:49.376+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-09T00:36:49.389+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-09T00:36:49.391+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
